import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Static assets (incl. locally-mirrored third-party CDN scripts) — not source.
    "public/**",
    // Auto-generated by scripts/convert.py — not hand-maintained source.
    "**/content.tsx",
    "src/lib/site-scripts.ts",
    "src/lib/blog-posts.ts",
  ]),
]);

export default eslintConfig;
